version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    command: npm start
    networks:
      - rabbitmq_nodejs

  database:
    image: mariadb:10.3
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./dbdata:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pdf-extraction-db
    networks:
      - rabbitmq_nodejs
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/mqdata/data/:/var/lib/rabbitmq/
      - ~/mqdata/log/:/var/log/rabbitmq
      - ~/mqdata/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ~/mqdata/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    networks:
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge
