version: "3"
services:
  app:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    command: npm start
  database:
    image: mariadb:10.3
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./dbdata:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pdf-extraction-db
  redis:
    image: redis
    command: redis-server --requirepass Redis2021!
    ports:
      - "6379:6379"
